[package]
authors = ["Jan Walter <jan@janwalter.com>"]
edition = "2018"
name = "pbrt"
version = "0.7.1"
[dependencies]
atom = "0.3.5"
atomic = "0.4"
bumpalo = "2.6"
byteorder = "1"
crossbeam = "0.7.2"
crossbeam-channel = "0.3"
getopts = "0.2"
half = "1"
hexf = "0.1.0"
image = "0.22"
lazy_static = "1.3.0"
num = "*"
num_cpus = "1.10"
pbr = "1.0"
pest = "2.1"
pest_derive = "2.1"
ply-rs = "0.1.2"
rayon = "1.1"
structopt = "0.3"
time = "0.1"
typed-arena = "1.4"

[[bin]]
name = "rs_pbrt"
path = "src/bin/rs_pbrt.rs"
